### ISSUE TITLE
Fix: command not found

### ISSUE THREAD

**Issue by Kaier33** [lehni/vscode-fix-checksums#3]
system version: macOS Mojave 10.14.6
Visual Studio Code version: 1.45.1

first step:          sudo "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"
second setp :    code --install-extension lehni.vscode-fix-checksums
when i  executing  "Fix Checksums: Apply" : 
Fix: command not found.

![image](https://user-images.githubusercontent.com/24623866/83129256-1bba5880-a10f-11ea-89d6-16c876aab565.png)

**Comment by v4de** [comment]
From your screenshot it looks like you are executing the command incorrectly. Need to execute from the command palette in vscode which is cmd+shift+p.

![image](https://user-images.githubusercontent.com/934222/98410227-44416980-2042-11eb-95c7-154965d6e467.png)

**Comment by AntonioL** [comment]
I am reproducing the above problem, while launching the extensions command using the palette.

**Comment by Kaier33** [comment]
> From your screenshot it looks like you are executing the command incorrectly. Need to execute from the command palette in vscode which is cmd+shift+p.
> 
> ![image](https://user-images.githubusercontent.com/934222/98410227-44416980-2042-11eb-95c7-154965d6e467.png)

it work for me , thanks
